---
commodities: ["auth", "db2_community", "nginx", "postgres-13", "rabbitmq", "redis", "squid", "swagger", "wiremock", "auth", "cadence", "cadence-web", "ibmmq", "activemq", "localstack"]

expensive_startup:
  - compose_service: common-dev-env-tester-app
    healthcheck_cmd: echo hello
    wait_until_healthy:
      - compose_service: db2_community
        healthcheck_cmd: docker
      - compose_service: postgres-13
        healthcheck_cmd: docker
