CREATE DATABASE TESTDB;

CONNECT TO TESTDB;

CREATE TABLE DISPATCHES (ID INTEGER, NAME VARCHAR(50), ADDRESS VARCHAR(255));

BEGIN ATOMIC DECLARE CNT INT DEFAULT 5; WHILE CNT < 100000 DO INSERT INTO DISPATCHES VALUES (CNT, 'HELLO', 'THIS IS AN ADDRESS'); SET CNT = CNT + 1; END WHILE;END

DISCONNECT TESTDB;
